name: Package Utilities_NetCore
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: powershell

jobs:
  package:
    runs-on: automate03-windows
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404'
          source-url: ${{ vars.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN_GITEA }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Create package
        run: dotnet pack --no-build -c Release -o out

      - name: Push package into registry
        run: dotnet nuget push "**/out/*.nupkg"
